version: 1

name: Negative Review Campaign Detection
description: |
  Detects coordinated negative review campaigns (review bombs) by analyzing review patterns.
  Identifies businesses receiving suspicious clusters of low-trust, negative reviews
  and automatically creates incidents for investigation.

  Detection Criteria:
  - recent_review_count >= 5 AND (rating_trend < -1.0 OR review_velocity > 2.0 OR suspicious_count > 3)

  Workflow Actions:
  1. Detect anomalous review patterns using ES|QL
  2. Create incidents for investigation
  3. Hold suspicious reviews
  4. Enable rating protection on affected businesses
  5. Notify stakeholders

  Integration:
  - This workflow can also be triggered via the API endpoint: POST /api/incidents/detect
  - Auto-detection is enabled on the GET /api/businesses/{id}/stats endpoint

enabled: true

# Configuration variables
config:
  elasticsearch_connector_id: "${ELASTICSEARCH_CONNECTOR_ID}"
  detection_window_minutes: 30
  min_review_count: 5
  low_trust_threshold: 0.4
  max_stars_threshold: 2

triggers:
  - type: schedule
    interval: 1m
  # Also trigger when webhook is called
  - type: webhook
    path: /workflow/review-bomb-detection/trigger

steps:
  # Step 1: Detect potential review bombs using ES|QL
  - id: detect_review_bombs
    type: elasticsearch.esql
    connectorId: "{{config.elasticsearch_connector_id}}"
    with:
      query: |
        FROM reviews
        | WHERE date > NOW() - 30 minutes
          AND stars <= 2
          AND (status == "pending" OR status IS NULL)
        | LOOKUP JOIN users ON user_id
        | WHERE trust_score < 0.4
        | STATS
            review_count = COUNT(*),
            avg_trust_score = AVG(trust_score),
            avg_stars = AVG(stars),
            unique_reviewers = COUNT_DISTINCT(user_id),
            review_ids = MV_SORT(VALUES(review_id))
          BY business_id
        | WHERE review_count >= 5
        | LOOKUP JOIN businesses ON business_id
        | KEEP business_id, name, review_count, avg_trust_score,
              avg_stars, unique_reviewers, review_ids, categories, city
        | RENAME name AS business_name, categories AS category
        | SORT review_count DESC

  # Step 2: Enrich each detected business with additional context
  - id: enrich_businesses
    type: foreach
    collection: "{{detect_review_bombs.results}}"
    as: attack
    steps:
      - id: get_business_details
        type: elasticsearch.esql
        connectorId: "{{config.elasticsearch_connector_id}}"
        with:
          query: |
            FROM businesses
            | WHERE business_id == "{{attack.business_id}}"
            | EVAL
                historical_avg_rating = COALESCE(avg_rating, 0.0),
                total_reviews = COALESCE(review_count, 0)
            | KEEP business_id, business_name, category, city, state,
                   historical_avg_rating, total_reviews, owner_user_id

      - id: get_recent_normal_reviews
        type: elasticsearch.esql
        connectorId: "{{config.elasticsearch_connector_id}}"
        with:
          query: |
            FROM reviews
            | WHERE business_id == "{{attack.business_id}}"
              AND date > NOW() - 7 days
            | LOOKUP JOIN users ON user_id
            | WHERE trust_score >= 0.6
            | STATS
                normal_review_count = COUNT(*),
                normal_avg_stars = AVG(stars)

  # Step 3: Create incident documents for each detected attack
  - id: create_incidents
    type: foreach
    collection: "{{detect_review_bombs.results}}"
    as: attack
    steps:
      - id: determine_severity
        type: if
        condition: "{{attack.review_count > 20}}"
        then:
          - id: set_critical
            type: set
            with:
              key: severity
              value: critical
        else:
          - id: check_high_severity
            type: if
            condition: "{{attack.review_count > 10}}"
            then:
              - id: set_high
                type: set
                with:
                  key: severity
                  value: high
            else:
              - id: set_medium
                type: set
                with:
                  key: severity
                  value: medium

      - id: create_incident_doc
        type: elasticsearch.index
        connectorId: "{{config.elasticsearch_connector_id}}"
        with:
          index: incidents
          document:
            incident_id: "INC-{{attack.business_id}}-{{execution.started_at | date('YYYYMMDDHHmmss')}}"
            incident_type: review_bomb
            status: open
            severity: "{{severity}}"
            business_id: "{{attack.business_id}}"
            business_name: "{{attack.business_name}}"
            category: "{{attack.category}}"
            city: "{{attack.city}}"
            detection_time: "{{execution.started_at}}"
            metrics:
              review_count: "{{attack.review_count}}"
              avg_trust_score: "{{attack.avg_trust_score}}"
              avg_stars: "{{attack.avg_stars}}"
              unique_reviewers: "{{attack.unique_reviewers}}"
            affected_review_ids: "{{attack.review_ids}}"
            created_at: "{{execution.started_at}}"
            updated_at: "{{execution.started_at}}"

  # Step 4: Hold affected reviews for investigation
  - id: hold_reviews
    type: foreach
    collection: "{{detect_review_bombs.results}}"
    as: attack
    steps:
      - id: update_reviews_to_held
        type: elasticsearch.update_by_query
        connectorId: "{{config.elasticsearch_connector_id}}"
        with:
          index: reviews
          query:
            bool:
              must:
                - term:
                    business_id: "{{attack.business_id}}"
                - range:
                    date:
                      gte: "now-30m"
                - range:
                    stars:
                      lte: 2
              should:
                - term:
                    status: "pending"
                - bool:
                    must_not:
                      - exists:
                          field: status
              minimum_should_match: 1
          script:
            source: |
              ctx._source.status = 'held';
              ctx._source.held_reason = 'review_bomb_detection';
              ctx._source.held_at = params.held_at;
            params:
              held_at: "{{execution.started_at}}"

  # Step 5: Enable rating protection on affected businesses
  - id: protect_businesses
    type: foreach
    collection: "{{detect_review_bombs.results}}"
    as: attack
    steps:
      - id: enable_rating_protection
        type: elasticsearch.update
        connectorId: "{{config.elasticsearch_connector_id}}"
        with:
          index: businesses
          id: "{{attack.business_id}}"
          document:
            rating_protected: true
            protection_enabled_at: "{{execution.started_at}}"
            protection_reason: review_bomb_detected

  # Step 6: Create notifications for stakeholders
  - id: create_notifications
    type: foreach
    collection: "{{detect_review_bombs.results}}"
    as: attack
    steps:
      - id: create_ops_notification
        type: elasticsearch.index
        connectorId: "{{config.elasticsearch_connector_id}}"
        with:
          index: notifications
          document:
            notification_id: "NOTIF-{{attack.business_id}}-{{execution.started_at | date('YYYYMMDDHHmmss')}}"
            notification_type: review_bomb_detected
            recipient_type: operations
            priority: "{{severity}}"
            title: "Negative Review Campaign Detected: {{attack.business_name}}"
            message: |
              A potential negative review campaign (review bomb) has been detected.

              Business: {{attack.business_name}}
              Location: {{attack.city}}
              Category: {{attack.category}}

              Attack Metrics:
              - Suspicious Reviews: {{attack.review_count}}
              - Average Trust Score: {{attack.avg_trust_score | round(2)}}
              - Average Stars: {{attack.avg_stars | round(1)}}
              - Unique Attackers: {{attack.unique_reviewers}}

              Actions Taken:
              - Reviews placed on hold
              - Business rating protection enabled
              - Incident created for investigation
            business_id: "{{attack.business_id}}"
            incident_id: "INC-{{attack.business_id}}-{{execution.started_at | date('YYYYMMDDHHmmss')}}"
            created_at: "{{execution.started_at}}"
            read: false

      - id: notify_business_owner
        type: elasticsearch.index
        connectorId: "{{config.elasticsearch_connector_id}}"
        with:
          index: notifications
          document:
            notification_id: "NOTIF-OWNER-{{attack.business_id}}-{{execution.started_at | date('YYYYMMDDHHmmss')}}"
            notification_type: rating_protection_enabled
            recipient_type: business_owner
            recipient_business_id: "{{attack.business_id}}"
            priority: high
            title: "Rating Protection Enabled for {{attack.business_name}}"
            message: |
              We've detected unusual review activity on your business listing and have
              temporarily enabled rating protection. This means recent suspicious reviews
              will not affect your displayed rating while our team investigates.

              No action is required from you at this time. We will notify you once
              the investigation is complete.
            created_at: "{{execution.started_at}}"
            read: false
